"""Aggiunta tabella GiornoFisso

Revision ID: 98719fe3bafc
Revises: 
Create Date: 2026-01-10 17:06:15.638893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98719fe3bafc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giorno_fisso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classe_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('giorno', sa.String(length=10), nullable=False),
    sa.Column('ore', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giorno_fisso')
    # ### end Alembic commands ###
