"""Add is_professionale to Materia

Revision ID: a0a49502cae5
Revises: ced5d0db3bfd
Create Date: 2026-01-23 16:38:00.325220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a49502cae5'
down_revision = 'ced5d0db3bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_professionale', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materia', schema=None) as batch_op:
        batch_op.drop_column('is_professionale')

    # ### end Alembic commands ###
